# Generated by Django 5.2.7 on 2025-11-07 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReporteEstatico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='reportes/estaticos/')),
                ('archivo_excel', models.FileField(blank=True, null=True, upload_to='reportes/estaticos/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='es_recurrente',
            field=models.BooleanField(default=False, help_text='Indica si el usuario es recurrente.'),
        ),
        migrations.AddField(
            model_name='venta',
            name='es_feriado',
            field=models.BooleanField(default=False, help_text='Indica si la venta se realizó en un feriado'),
        ),
        migrations.AlterField(
            model_name='notificacionpush',
            name='tipo',
            field=models.CharField(default='sistema', max_length=50),
        ),
        migrations.AlterField(
            model_name='ventaproducto',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_vendidos', to='app.venta'),
        ),
        migrations.CreateModel(
            name='ReporteDinamico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('parametros', models.JSONField(help_text='Parámetros utilizados para generar el reporte')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='reportes/dinamicos/')),
                ('archivo_excel', models.FileField(blank=True, null=True, upload_to='reportes/dinamicos/')),
                ('estado', models.CharField(choices=[('generado', 'Generado'), ('en_proceso', 'En Proceso')], max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReporteIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('datos_entrada', models.JSONField(help_text='Datos utilizados para alimentar el modelo de IA')),
                ('resultado_ia', models.JSONField(help_text='Resultado generado por el modelo de IA (recomendaciones, análisis)')),
                ('modelo_ia', models.CharField(help_text='Nombre del modelo de IA utilizado', max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='reportes/ia/')),
                ('archivo_excel', models.FileField(blank=True, null=True, upload_to='reportes/ia/')),
                ('estado', models.CharField(choices=[('generado', 'Generado'), ('en_proceso', 'En Proceso')], max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
