# Generated by Django 5.2.7 on 2025-10-17 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.DateTimeField()),
                ('logout', models.DateTimeField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, help_text='Dirección IPv4 o IPv6 del dispositivo', null=True)),
                ('device', models.CharField(blank=True, help_text="Ubicación aproximada (p.ej. 'Ciudad, País' o 'lat,lon')", max_length=255, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bitacora',
            },
        ),
        migrations.CreateModel(
            name='DetalleBitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField()),
                ('tabla', models.CharField(max_length=50)),
                ('bitacora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detallebitacoras', to='app.bitacora')),
            ],
            options={
                'db_table': 'detallebitacora',
            },
        ),
        migrations.CreateModel(
            name='DispositivoMovil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_fcm', models.TextField(help_text='Token de Firebase Cloud Messaging para enviar notificaciones push', unique=True)),
                ('modelo_dispositivo', models.CharField(blank=True, help_text='Ej: iPhone 14, Samsung Galaxy S23', max_length=255, null=True)),
                ('sistema_operativo', models.CharField(blank=True, help_text='iOS, Android, etc.', max_length=50, null=True)),
                ('activo', models.BooleanField(default=True, help_text='Indica si el dispositivo sigue recibiendo notificaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ultima_conexion', models.DateTimeField(blank=True, help_text='Última vez que la app se conectó o renovó el token', null=True)),
                ('usuario', models.ForeignKey(help_text='Usuario propietario del dispositivo', on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dispositivo Móvil',
                'verbose_name_plural': 'Dispositivos Móviles',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='NotificacionPush',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('cuerpo', models.TextField()),
                ('tipo', models.CharField(choices=[('seguridad', 'Seguridad'), ('finanzas', 'Finanzas'), ('areas_comunes', 'Áreas Comunes'), ('mantenimiento', 'Mantenimiento'), ('comunicado', 'Comunicado'), ('sistema', 'Sistema')], default='sistema', max_length=50)),
                ('estado', models.CharField(choices=[('enviada', 'Enviada'), ('entregada', 'Entregada'), ('leida', 'Leída'), ('fallida', 'Fallida')], default='enviada', max_length=20)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, help_text='Cuando FCM confirma entrega', null=True)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('datos_adicionales', models.JSONField(blank=True, help_text='Payload adicional (ej: id de incidente, url, acción)', null=True)),
                ('intento_envio', models.PositiveSmallIntegerField(default=1)),
                ('dispositivo', models.ForeignKey(blank=True, help_text='Dispositivo al que se envió la notificación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_enviadas', to='app.dispositivomovil')),
                ('usuario', models.ForeignKey(help_text='Usuario destinatario de la notificación', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_push', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación Push',
                'verbose_name_plural': 'Notificaciones Push',
                'ordering': ['-fecha_envio'],
            },
        ),
    ]
